### ISSUE TITLE
bug: outdated magnitude terms (la, sa)

### ISSUE THREAD

**Issue by TallKite** [m-yac/microtonal-utils#3]
large should be la-, e.g. 81/64 = lawa 3rd
small should be sa-, e.g. 128/64 = sawa 6th
multi-magnitudes work exactly like multi-colors:
2-large should be lala-
3-large should be trila-
4-large should be quadla-
etc.

**Comment by m-yac** [comment]
Fixed in ed9888230a0374cc02a155f2d0975c8e5e26c48b.
